### ISSUE TITLE
ak.* support for typetracer arrays

### ISSUE THREAD

**Issue by douglasdavis** [scikit-hep/awkward#1504]
### Description of new feature

Running list of (discovered by trying in dask-awkward) missing functions:
- [ ] `ones_like`
- [ ] `zeros_like`
- [ ] `firsts`

Example failure:
```python
>>> import awkward._v2 as ak
>>> ak.ones_like(ak.Array(ak.Array([1, 2, 3]).layout.typetracer))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ddavis/.pyenv/versions/dask-dev/lib/python3.10/site-packages/awkward/_v2/operations/ak_ones_like.py", line 30, in ones_like
    return _impl(array, highlevel, behavior, dtype)
  File "/Users/ddavis/.pyenv/versions/dask-dev/lib/python3.10/site-packages/awkward/_v2/operations/ak_ones_like.py", line 34, in _impl
    return ak._v2.operations.ak_full_like._impl(array, 1, highlevel, behavior, dtype)
  File "/Users/ddavis/.pyenv/versions/dask-dev/lib/python3.10/site-packages/awkward/_v2/operations/ak_full_like.py", line 177, in _impl
    out = layout.recursively_apply(action)
  File "/Users/ddavis/.pyenv/versions/dask-dev/lib/python3.10/site-packages/awkward/_v2/contents/content.py", line 1326, in recursively_apply
    return self._recursively_apply(
  File "/Users/ddavis/.pyenv/versions/dask-dev/lib/python3.10/site-packages/awkward/_v2/contents/numpyarray.py", line 1296, in _recursively_apply
    result = action(
  File "/Users/ddavis/.pyenv/versions/dask-dev/lib/python3.10/site-packages/awkward/_v2/operations/ak_full_like.py", line 164, in action
    nplike.ones_like(original),
  File "/Users/ddavis/.pyenv/versions/dask-dev/lib/python3.10/site-packages/awkward/_v2/_typetracer.py", line 531, in ones_like
    raise ak._v2._util.error(NotImplementedError)
NotImplementedError:
```

**Comment by jpivarski** [comment]
I made this the [top priority](https://github.com/scikit-hep/awkward/projects/5) of the "easy" column, hoping that @ioanaif, @agoose77, or @ianna can get to it soon. I think that `ones_like` and `zeros_like` will have exactly the same implementation for the TypeTracer. `firsts` is a higher-level function, but it's blocked by `ones_like` and `zeros_like`, right?

**Comment by douglasdavis** [comment]
I don't think `firsts` is blocked by anything; and just to be clear all 3 of the functions I've found so far are working in dask-awkward fine as a dak.* equivalent (it's just that in these cases where the function fails on the old typetracer, the new typetracer is derived (triggering a warning) via the ["backup method"](https://github.com/ContinuumIO/dask-awkward/blob/440a47dff6489c73165b114e473562741e39f266/src/dask_awkward/core.py#L1122-L1128)-- from the computation of the first partition instead of from calling the ak.* function, since `new_meta = f(old_array._meta)` failed).
