### ISSUE TITLE
NEP 18 overloaded functions don't have same function signature

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/awkward#2088]
### Version of Awkward Array

main

### Description and code to reproduce

Our `ak.*` NEP-18 overloaded functions do not directly copy the NumPy function signatures, e.g.:

```python
@ak._connect.numpy.implements("std")
def std(
    x,
    weight=None,
    ddof=0,
    axis=None,
    *,
    keepdims=False,
    mask_identity=False,
    flatten_records=unset,
):
```
vs NumPy's
```python
@array_function_dispatch(_std_dispatcher)
def std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=np._NoValue, *,
        where=np._NoValue):
```

Understandably, we don't want to have NumPy-only parameters in our signatures, e.g. `out=`. However, this means that positional arguments are not guaranteed to match-up with Awkward. For example in this case, passing `axis` by position to `np.std` would not work, i.e.
```pycon
>>> np.std(ak.to_numpy(x), -1)
0.816496580927726
>>> np.std(x, -1)
Traceback (most recent call last):
  File "/home/angus/.mambaforge/envs/awkward/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3442, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-0b53e1f1071f>", line 1, in <module>
    np.std(x, -1)
  File "<__array_function__ internals>", line 200, in std
  File "/home/angus/Git/awkward/src/awkward/highlevel.py", line 1411, in __array_function__
    return ak._connect.numpy.array_function(
  File "/home/angus/Git/awkward/src/awkward/_connect/numpy.py", line 59, in array_function
    return function(*args, **kwargs)
  File "/home/angus/Git/awkward/src/awkward/operations/ak_std.py", line 84, in std
    return _impl(x, weight, ddof, axis, keepdims, mask_identity)
  File "/home/angus/Git/awkward/src/awkward/operations/ak_std.py", line 168, in _impl
    ak.operations.to_layout(weight, allow_record=False, allow_other=False),
  File "/home/angus/Git/awkward/src/awkward/operations/ak_to_layout.py", line 39, in to_layout
    return _impl(array, allow_record, allow_other)
  File "/home/angus/Git/awkward/src/awkward/operations/ak_to_layout.py", line 124, in _impl
    raise _errors.wrap_error(
TypeError: while calling
    ak.std(
        x = <Array [[1, 2, 3]] type='1 * var * int64'>
        weight = -1
        ddof = 0
        axis = None
        keepdims = False
        mask_identity = False
    )
Error details: -1 cannot be converted into an Awkward Array
```

Most of the time this isn't a problem; in practice, the NumPy `out` parameter appears early in the argument list, which immediately breaks any subsequent positional correspondence.

I think, in general, we can improve this. If we bind the parameters to the signature of the _NumPy_ function, we can then pass them into the appropriate Awkward order. If we assert that the Awkward function has no position-only parameters, then this would be trivial; pass in the bound parameters as keyword arguments.

**Comment by agoose77** [comment]
Here's a modified `ak._connect.numpy.implements` that would enforce the correspondence between `POSITIONAL_OR_KEYWORD` arguments:
```python
def implements(numpy_function):
    def decorator(function):
        numpy_function_impl = getattr(numpy, numpy_function)
        numpy_signature = inspect.signature(numpy_function_impl)
        awkward_signature = inspect.signature(function)

        # Require that any NumPy arguments that are required, but can be
        # passed by keyword, exist in the Awkward signature, with the same
        # names
        for np_param, ak_param in itertools.zip_longest(
            numpy_signature.parameters.values(), awkward_signature.parameters.values()
        ):
            assert np_param is not None
            if ak_param is None:
                break

            # Don't care about names, they can't be used
            if np_param.kind == np_param.POSITIONAL_ONLY:
                continue

            # Require that we use same names at same positions
            elif np_param.kind == np_param.POSITIONAL_OR_KEYWORD:
                assert (
                    np_param.name == ak_param.name
                ), f"Awkward NEP-function {numpy_function!r} uses a different argument name for NumPy's position-only " \
                   f"counterpart: {np_param.name!r}"

            else:
                break

        implemented[numpy_function_impl] = function
        return function

    return decorator
```

**Comment by agoose77** [comment]
This issue ties in slightly with #2045 and #2079. I think it might be safer / easier to write explicit NEP-18 overloads for our functions, which would be more robust and properly honour the supported signature of the NumPy functions without requiring us to bend our Awkward API. E.g.

```python
def std(
    x,
    weight=None,
    ddof=0,
    axis=None,
    *,
    keepdims=False,
    mask_identity=False,
    flatten_records=unset,
):
    ...
    
    
@ak._connect.numpy.implements("std")
def _nep_18_impl(
    a, axis=None, dtype=unsupported, out=unsupported, ddof=0, keepdims=False, *, where=unsupported
):
    nplike = ak._nplikes.nplike_of(a)
    behavior = ak._util.behaviorof(a)
    out = std(
        a=a, 
        keepdims=keepdims,
        ddof=ddof,
        keepdims=keepdims
    )
    return ak._util.wrap(out, behavior=behavior)
```

We could modify `implements(...)` so that it handles the boilerplate of non-existent arguments (`unsupported`). Any more advanced validation should occur in the `_nep_18_impl` function.
