### ISSUE TITLE
TypeTracers do not pass through ak.num

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#2092]
### Version of Awkward Array

2.0.5

### Description and code to reproduce

```python3
import awkward as ak
import dask_awkward as dak

x = ak.Array([[1, 2, 3],[4],[5,6]])
tt = dak.typetracer_from_form(x.layout.form)
print(ak.num(tt))
```
results in:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_num.py", line 71, in num
    return _impl(array, axis, highlevel, behavior)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_num.py", line 100, in _impl
    out = ak._do.recursively_apply(layout, action, behavior, numpy_to_regular=True)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_do.py", line 34, in recursively_apply
    return layout._recursively_apply(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/contents/listoffsetarray.py", line 2051, in _recursively_apply
    result = action(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_num.py", line 93, in action
    return ak.contents.NumpyArray(layout.stops.data - layout.starts.data)
TypeError: unsupported operand type(s) for -: 'TypeTracerArray' and 'TypeTracerArray'
```

**Comment by lgray** [comment]
Ah, this is a duplicate of #1997 , effectively.
