### ISSUE TITLE
Status of Numba support

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/awkward#221]
Sorry if I miss some obvious information: I just worked through the demo notebook for Numba developers (https://github.com/scikit-hep/awkward-1.0/blob/master/docs-demo-notebooks/2020-01-22-numba-demo-EVALUATED.ipynb) and could not run the numba example. I also was not able to install the exact version required as it is not on PyPI (`pip install 'awkward1==0.1.87'`), so I tried one above and one below (`0.1.92` and `0.1.38`) but got the same message (see below).

What is the actual status of the Numba support? In the notebook it seems that for array layouts it already worked quite well, which I really look forward to! Is there a new way of providing the Awkward1 structures?

My original problem btw. is the lack of a `np.unique` utility function for which I'll open a new issue or PR if I find more time, so I thought I'll quickly hack together a JITted function.

```python
import numba as nb

@nb.jit(nopython=True)
def run(array):
    out = np.empty(len(array), np.float64)
    for i in range(len(array)):
        out[i] = array[i]["x"]
        for y in array[i]["y"]:
            out[i] += y
    return out

akarray = ak.Array([{"x": 100, "y": [1.1, 2.2]}, {"x": 200, "y": []}, {"x": 300, "y": [3.3]}])

# Works for the layout nodes, but not the high-level ak.Array wrapper yet.
run(akarray.layout)
```

gives (this is with `awkward=='0.2.16'` and `numba=='0.49.0'` but the error was similar for older Awkward versions and also older versions of Numba):

```python
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-5-34ffcbcddf9c> in <module>
     13 
     14 # Works for the layout nodes, but not the high-level ak.Array wrapper yet.
---> 15 run(akarray.layout)

~/Dev/km3io/venv/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    399                 e.patch_message(msg)
    400 
--> 401             error_rewrite(e, 'typing')
    402         except errors.UnsupportedError as e:
    403             # Something unsupported is present in the user code, add help info

~/Dev/km3io/venv/lib/python3.8/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345 
    346         argtypes = []

~/Dev/km3io/venv/lib/python3.8/site-packages/numba/core/utils.py in reraise(tp, value, tb)
     77         value = tp()
     78     if value.__traceback__ is not tb:
---> 79         raise value.with_traceback(tb)
     80     raise value
     81 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function len>) with argument(s) of type(s): (awkward1.RecordArrayType((awkward1.NumpyArrayType(array(int64, 1d, C), none, {}), awkward1.ListArrayType(array(int64, 1d, C), awkward1.NumpyArrayType(array(float64, 1d, C), none, {}), none, {})), (('x', 'y')), none, {}))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
In definition 12:
    All templates rejected with literals.
In definition 13:
    All templates rejected without literals.
In definition 14:
    All templates rejected with literals.
In definition 15:
    All templates rejected without literals.
In definition 16:
    All templates rejected with literals.
In definition 17:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function len>)
[2] During: typing of call at <ipython-input-5-34ffcbcddf9c> (5)


File "<ipython-input-5-34ffcbcddf9c>", line 5:
def run(array):
    out = np.empty(len(array), np.float64)
    ^
```

I also tried getting rid of `len(array)` to see where it chokes but it seem that the index accessing is already causing trouble, as seen by this tiny example:

```python
import numba as nb

@nb.jit(nopython=True)
def run(array):
    out = np.empty(3)
    for i in range(3):
        out[i] = array[i]
    return out

akarray = ak.Array([1, 2, 3])

# Works for the layout nodes, but not the high-level ak.Array wrapper yet.
run(akarray.layout)
```

which gives:

```python
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-9-09f2be2cb22a> in <module>
     11 
     12 # Works for the layout nodes, but not the high-level ak.Array wrapper yet.
---> 13 run(akarray.layout)

~/Dev/km3io/venv/lib/python3.8/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    399                 e.patch_message(msg)
    400 
--> 401             error_rewrite(e, 'typing')
    402         except errors.UnsupportedError as e:
    403             # Something unsupported is present in the user code, add help info

~/Dev/km3io/venv/lib/python3.8/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345 
    346         argtypes = []

~/Dev/km3io/venv/lib/python3.8/site-packages/numba/core/utils.py in reraise(tp, value, tb)
     77         value = tp()
     78     if value.__traceback__ is not tb:
---> 79         raise value.with_traceback(tb)
     80     raise value
     81 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (awkward1.NumpyArrayType(array(int64, 1d, C), none, {}), int64)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
In definition 12:
    All templates rejected with literals.
In definition 13:
    All templates rejected without literals.
In definition 14:
    All templates rejected with literals.
In definition 15:
    All templates rejected without literals.
In definition 16:
    All templates rejected with literals.
In definition 17:
    All templates rejected without literals.
In definition 18:
    All templates rejected with literals.
In definition 19:
    All templates rejected without literals.
In definition 20:
    All templates rejected with literals.
In definition 21:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at <ipython-input-9-09f2be2cb22a> (7)

File "<ipython-input-9-09f2be2cb22a>", line 7:
def run(array):
    <source elided>
    for i in range(3):
        out[i] = array[i]
        ^
```

**Comment by jpivarski** [comment]
The demo explicitly requires an old version of Awkward (what was current at the time of the demo, which is entirely replaced now) and implicitly requires a <0.49 version of Numba, because we didn't know the change was coming.

**Comment by tamasgal** [comment]
Yes, I think I also tried Numba 0.47 and Awkward1==0.1.92 and 0.1.38 but I could not get it work. I did not make the effort tot install the mid-version though 🙈 

Anyways, is there a new method to invoke this functionality or is this currently under reconstruction?

Edit: forgot to mention that I also looked at the tests but I could not find an obvious way how to utilise the Numba functionality. I am of course aware that the documentation is currently under development! Sorry for being impatient 😉

**Comment by jpivarski** [comment]
I just checked your code sample, copied from the notebook.

```python
# Works for the layout nodes, but not the high-level ak.Array wrapper yet.
```

Now the inverse is true—it only works for ak.Array and not the layout nodes. The Awkward-Numba interface was entirely rewritten after that talk, responding to feedback from the Numba team. (Now we're not even passing layout nodes through Numba; it's more of a pointer starting from the root of the ak.Array because this avoids copying large structures repeatedly.)

Here is a better demo to start from, presented one or two weeks ago: https://github.com/jpivarski/2020-04-08-eic-jlab#readme I froze function names before this new demo, so it's more forward-looking.

**Comment by tamasgal** [comment]
Indeed, omg that's a bit embarrassing. Of course I first tried to naively use them in Numba, which failed (surely my mistake) then searched for the docs and fixated on the Layout-stuff.

Thanks! Also for the new demo :)
