### ISSUE TITLE
Indexing operations on regular array typetracer fails

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#2222]
### Version of Awkward Array

awkward@main + dask_awkward@refactor-column-optimization

### Description and code to reproduce

```python3
import awkward as ak
import dask_awkward as dak

x = ak.to_regular(ak.Array([[[-1, 1.], [-2, 2], [-3, 3]], [[-4, 4]], []]), axis=-1)
dx = dak.from_awkward(x, 1)
dx._meta[:, -1]
```

results in:
```
Traceback (most recent call last):
  File "regular_array_problem.py", line 6, in <module>
    dx._meta[:, -1]
  File "/Users/lgray/coffea-dev/awkward/src/awkward/highlevel.py", line 951, in __getitem__
    out = self._layout[where]
  File "/Users/lgray/coffea-dev/awkward/src/awkward/contents/content.py", line 514, in __getitem__
    return self._getitem(where)
  File "/Users/lgray/coffea-dev/awkward/src/awkward/contents/content.py", line 551, in _getitem
    out = next._getitem_next(nextwhere[0], nextwhere[1:], None)
  File "/Users/lgray/coffea-dev/awkward/src/awkward/contents/regulararray.py", line 393, in _getitem_next
    start, stop, step = head.indices(self._size)
```

**Comment by lgray** [comment]
As a side note - this problem also appears in awkward `2.0.7` on PyPI as well.

**Comment by agoose77** [comment]
Related to #2223

**Comment by lgray** [comment]
FYI with #2223 merged this error still occurs

**Comment by agoose77** [comment]
Yes, that PR ended up being split into two parts for review. #2220 should be the one that starts to fix this.
