### ISSUE TITLE
Installation fails on python 3.7 due to unparsable pyproject.toml

### ISSUE THREAD

**Issue by rklasen** [scikit-hep/awkward#2253]
### Version of Awkward Array

n.a.

### Description and code to reproduce

Hi,

The current version of awkward can't be be built in my docker image. It's been a while since I last built it, but I suspect it's due to the separation of awkward and awkward cpp.

Back story: I'm the maintainer of [Pandas Luminosity Fit](https://github.com/panda-luminosity-detector-group/LuminosityFit), and inside our docker image (based on debian 10 with python 3.7 installed, see the [docker file](https://github.com/panda-luminosity-detector-group/LuminosityFit/tree/master/docker)) the installation fails with the error:

```python
Collecting awkward-cpp==9 (from awkward->-r /tmp/requirements.txt (line 12))
  Downloading https://files.pythonhosted.org/packages/5c/ed/9ea65e3121ca03b329734a45c17b4ba0cda78345f533ba43a30dc9fd4dd8/awkward-cpp-9.tar.gz (1.4MB)
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 100, in prep_for_dist
    self.req.load_pyproject_toml()
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 428, in load_pyproject_toml
    str(self)
  File "/usr/lib/python3/dist-packages/pip/_internal/pyproject.py", line 43, in load_pyproject_toml
    pp_toml = pytoml.load(f)
  File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 303, in load
    filename=fin.name)
  File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 370, in loads
    toks.expect('=', 'expected_equals')
  File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 250, in expect
    self.error(error_text)
  File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 253, in error
    raise TomlError(message, self.pos[0][0], self.pos[0][1], self._filename)
pytoml.core.TomlError: /tmp/pip-install-dl3m19jx/awkward-cpp/pyproject.toml(62, 6): expected_equals
```

I suspect the pytoml to be [this file](https://github.com/scikit-hep/awkward/blob/main/awkward-cpp/pyproject.toml) one, and in line 62 at position 6 there is a minus sign:

```toml
build-dir = "build/{cache_tag}"
```

I don't know enough about toml to say whether that minus sign is allowed in identifiers, but obviously you tested the build process, so I'm not sure why it fails for me.

EDIT: on the official TOML homepage, the examples only have underscores, not minuses or dashes:

```toml
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }
```

Can you give me a pointer how to debug this?

Best wishes!

**Comment by rklasen** [comment]
Okay I've just read the [specs](https://toml.io/en/v1.0.0#keys) and dashes and minuses are allowed. So maybe the pytoml parser of 3.7 can't handle them?

**Comment by agoose77** [comment]
`pytoml` is deprecated, I wonder what version of `pip` you are using? It looks like it's coming via pip.

**Comment by agoose77** [comment]
Wait a minute, I wonder why you're being given an sdist for building rather than a wheel? I can't remember off the top of my head which platforms support manylinux, but I would assume yours did. Do you expect this?

**Comment by rklasen** [comment]
Thanks for the quick reply. The base image is Debian Buster, so 10. 

I just tested with a fresh debian base image. I installed python 2.7 via `apt update && apt install python-pip`, and the installation went without issue:

```
root@e41fd581e9d0:/# pip install awkward
Collecting awkward
  Downloading https://files.pythonhosted.org/packages/75/04/50aa6af8e38066c90f6e1da241c17f6cd522643ce6d587b60ccf43f15fe5/awkward-1.7.0-cp27-cp27mu-manylinux1_x86_64.whl (13.7MB)
    100% |################################| 13.7MB 76kB/s 
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from awkward) (40.8.0)
Collecting numpy>=1.13.1 (from awkward)
  Downloading https://files.pythonhosted.org/packages/3a/5f/47e578b3ae79e2624e205445ab77a1848acdaa2929a00eeef6b16eaaeb20/numpy-1.16.6-cp27-cp27mu-manylinux1_x86_64.whl (17.0MB)
    100% |################################| 17.0MB 53kB/s 
Installing collected packages: numpy, awkward
Successfully installed awkward-1.7.0 numpy-1.16.6
```

---

Now, with a fresh debian buster but installing python 3.7 via `apt update && apt install python3-pip`, the installation fails:

```
root@762a842df444:/# apt update && apt install python3-pip
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [56.6 kB]
Get:4 http://deb.debian.org/debian buster/main amd64 Packages [7909 kB]
Get:5 http://deb.debian.org/debian-security buster/updates/main amd64 Packages [433 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [8788 B]
Fetched 8564 kB in 5s (1870 kB/s)  
[...]

LOTS of packages
[...]
Running hooks in /etc/ca-certificates/update.d...
done.
```

Then `awkward`:

```
root@762a842df444:/# pip3 install awkward
Collecting awkward
  Downloading https://files.pythonhosted.org/packages/42/2f/a137a7f70afb7d810610275946e50f000900dd6f0442b293ac29cd742922/awkward-2.0.8-py3-none-any.whl (583kB)
    100% |████████████████████████████████| 583kB 1.2MB/s 
Collecting awkward-cpp==9 (from awkward)
  Downloading https://files.pythonhosted.org/packages/5c/ed/9ea65e3121ca03b329734a45c17b4ba0cda78345f533ba43a30dc9fd4dd8/awkward-cpp-9.tar.gz (1.4MB)
    100% |████████████████████████████████| 1.4MB 404kB/s 
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 338, in run
    resolver.resolve(requirement_set)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 100, in prep_for_dist
    self.req.load_pyproject_toml()
  File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 428, in load_pyproject_toml
    str(self)
  File "/usr/lib/python3/dist-packages/pip/_internal/pyproject.py", line 43, in load_pyproject_toml
    pp_toml = pytoml.load(f)
  File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 303, in load
    filename=fin.name)
  File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 370, in loads
    toks.expect('=', 'expected_equals')
  File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 250, in expect
    self.error(error_text)
  File "/usr/share/python-wheels/pytoml-0.1.2-py2.py3-none-any.whl/pytoml/parser.py", line 253, in error
    raise TomlError(message, self.pos[0][0], self.pos[0][1], self._filename)
pytoml.core.TomlError: /tmp/pip-install-p8py33yz/awkward-cpp/pyproject.toml(62, 6): expected_equals
```

So it seems to be with default debian 10 and it's version of python3.

**Comment by agoose77** [comment]
I took a look at [the manylinux information](https://github.com/pypa/manylinux), and it looks like your pip version is too old to use manylinux>1. I would suggest not installing `python3-pip`, and instead installing `pip` with `get-pip`. That way you can work with a much newer version according to the compatibility in the link above. 

Could you try that and let me know how you get on?

**Comment by agoose77** [comment]
Closing this as it's a tooling problem rather than something that we can fix. Feel free to reopen if you feel that's not the case :)

**Comment by rklasen** [comment]
Sorry I didn't get around to answering earlier :sweat_smile: Thanks for the hints, I'll try that. If I run into any more problems, I'll update this issue.

Thanks!

EDIT: yup, using `get-pip` on Debian 10 instead of installing `python3-pip` solved the issue.
