### ISSUE TITLE
Awkward allows non-nullable unknown type, but Arrow doesn't

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2340]
In trying to construct a minimal reproducer, I find that they directly forbid a null type from being non-nullable:

```python
>>> import pyarrow as pa
>>> pa.field("name", pa.null(), nullable=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/types.pxi", line 2266, in pyarrow.lib.field
ValueError: A null type field may not be non-nullable
```

In our code, we must be getting at it some other way that bypasses this check, but it's clear what their intentions are. We _do_ allow an `UnknownType` to not be inside an `OptionType`, so the problem is that we have a broader type system and a direct conversion makes something that Arrow doesn't consider legal.

So the right way to fix this is to wrap our `EmptyArray` inside `UnmaskedArray` on conversion to Arrow, but include enough metadata in the `ExtensionType` that when we convert it back, we know to remove the option-type, so that it's round-trip preserved. I'll make this an issue.

_Originally posted by @jpivarski in https://github.com/scikit-hep/awkward/issues/2337#issuecomment-1482892635_

**Comment by tcawlfield** [comment]
I guess part of this bugfix is to allow round-tripping with an unknown type:
```
>>> a1 = ak.Array([])
>>> a1
<Array [] type='0 * unknown'>
>>> arw1 = ak.to_arrow(a1)
>>> arw1
<awkward._connect.pyarrow.AwkwardArrowArray object at 0x7fac33514040>
0 nulls
>>> a1_again = ak.from_arrow(arw1)
<exception thrown currently but this is the bug.>
```

And perhaps similar results with unknown arrays embedded within other record structures.

**Comment by jpivarski** [comment]
Interestingly, while pyarrow prevents you from making a non-nullable null type (a triple-negative!),

```python
>>> import pyarrow as pa
>>> pa.field("name", pa.null(), nullable=False)
```

raises

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/types.pxi", line 2266, in pyarrow.lib.field
ValueError: A null type field may not be non-nullable
```

you _can_ make one as a part of the process of converting an Awkward Array:

```python
>>> import awkward as ak
>>> ak_array = ak.Array([[], [], []])
>>> arrow_array = ak.to_arrow(ak_array, list_to32=True, extensionarray=False)
>>> the_field_pyarrow_cant_make = arrow_array.type.field(0)
>>> the_field_pyarrow_cant_make
pyarrow.Field<item: null not null>
>>> the_field_pyarrow_cant_make.nullable
False
>>> the_field_pyarrow_cant_make.type
DataType(null)
```

The Awkward code gets there by a different code-path:

```python
>>> pa.field("name", pa.null(), nullable=False)        # not allowed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/types.pxi", line 3404, in pyarrow.lib.field
ValueError: A null type field may not be non-nullable

>>> pa.field("name", pa.null()).with_nullable(False)   # equivalent, but allowed
pyarrow.Field<name: null not null>
```

I guess what's happening here is that non-nullable null types are not allowed in Arrow, but they're insufficiently protected. (I'll submit a pyarrow bug-report about this alternate path to getting non-nullable null type.)

There _might_ be bad consequences with these types in Arrow itself, but there is definitely a bad consequence when trying to write the data as Parquet:

```python
>>> ak.to_parquet(ak_array, "/tmp/whatever.parquet", list_to32=True, extensionarray=False)
```

raises

```
Traceback (most recent call last):
  File "/home/jpivarski/irishep/awkward/src/awkward/_dispatch.py", line 64, in dispatch
    next(gen_or_result)
  File "/home/jpivarski/irishep/awkward/src/awkward/operations/ak_to_parquet.py", line 183, in to_parquet
    return _impl(
  File "/home/jpivarski/irishep/awkward/src/awkward/operations/ak_to_parquet.py", line 416, in _impl
    with pyarrow_parquet.ParquetWriter(
  File "/home/jpivarski/mambaforge/lib/python3.10/site-packages/pyarrow/parquet/core.py", line 1010, in __init__
    self.writer = _parquet.ParquetWriter(
  File "pyarrow/_parquet.pyx", line 2157, in pyarrow._parquet.ParquetWriter.__cinit__
  File "pyarrow/error.pxi", line 154, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 91, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: NullType Arrow field must be nullable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/awkward/src/awkward/_dispatch.py", line 38, in dispatch
    with OperationErrorContext(name, args, kwargs):
  File "/home/jpivarski/irishep/awkward/src/awkward/_errors.py", line 85, in __exit__
    self.handle_exception(exception_type, exception_value)
  File "/home/jpivarski/irishep/awkward/src/awkward/_errors.py", line 95, in handle_exception
    raise self.decorate_exception(cls, exception)
pyarrow.lib.ArrowInvalid: NullType Arrow field must be nullable

This error occurred while calling

    ak.to_parquet(
        <Array [[], [], []] type='3 * var * unknown'>
        '/tmp/whatever.parquet'
        list_to32 = True
        extensionarray = False
    )
```
