### ISSUE TITLE
ak.concatenate does not work on RegularArray typetracers

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#2495]
### Version of Awkward Array

2.2.1

### Description and code to reproduce

```python3
import awkward as ak
import numpy as np

fromdict = {
    "class": "RegularArray",
    "size": 100,
    "len": 0,
    "content": {
        "class": "NumpyArray",
        "primitive": "float32",
        "inner_shape": [],
        "parameters": {},
        "form_key": "",
    }
}


form = ak.forms.from_dict(fromdict)

ttarray = ak.Array(
    form.length_zero_array(highlevel=False).to_typetracer(forget_length=True)
)

# neither of the following function, both are needed in typical
# ak -> numpy -> ML algorithm -> numpy -> ak transformations
ak.concatenate([ttarray], axis=1)

ak.concatenate([ttarray[:, np.newaxis, :]], axis=1)
```

results in:
```
Traceback (most recent call last):
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_concatenate.py", line 51, in concatenate
    return _impl(arrays, axis, mergebool, highlevel, behavior)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_concatenate.py", line 279, in _impl
    out = ak._broadcasting.broadcast_and_apply(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_broadcasting.py", line 1079, in broadcast_and_apply
    out = apply_step(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_broadcasting.py", line 1058, in apply_step
    return continuation()
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_broadcasting.py", line 1031, in continuation
    return broadcast_any_list()
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_broadcasting.py", line 581, in broadcast_any_list
    outcontent = apply_step(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_broadcasting.py", line 1044, in apply_step
    result = action(
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_concatenate.py", line 193, in action
    tags = ak.index.Index8(backend.index_nplike.tile(prototype, length))
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_nplikes/typetracer.py", line 1099, in tile
    raise NotImplementedError
NotImplementedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "form_madness11.py", line 25, in <module>
    ak.concatenate([ttarray], axis=1)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/operations/ak_concatenate.py", line 51, in concatenate
    return _impl(arrays, axis, mergebool, highlevel, behavior)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_errors.py", line 56, in __exit__
    self.handle_exception(exception_type, exception_value)
  File "/Users/lgray/miniforge3/envs/coffea-dev/lib/python3.8/site-packages/awkward/_errors.py", line 71, in handle_exception
    raise self.decorate_exception(cls, exception)
NotImplementedError: 

See if this has been reported at https://github.com/scikit-hep/awkward/issues
```

**Comment by agoose77** [comment]
I'll take a look! By the way, you can use `ak.forms.from_dict` instead of `from_json` to avoid the JSON serialisation :)
