### ISSUE TITLE
TypeError when summing regular array of unknown length

### ISSUE THREAD

**Issue by jrueb** [scikit-hep/awkward#2607]
### Version of Awkward Array

2.3.1

### Description and code to reproduce

```python
import awkward as ak


x = ak.to_regular(ak.Array([[1.]])[[[False]]])
t = ak.Array(x.layout.to_typetracer(forget_length=True))
ak.sum(t, axis=1)
```
The last line raises an error: `TypeError: cannot compare unknown lengths against known values`.
It works fine when x is not regular, meaning `x = ak.Array([[1.]])[[[False]]]`.
In my case, this breaks dask-awkward functionality when trying to sum over regular dask-awkward arrays.

**Comment by jpivarski** [comment]
The debugging part of the exception stack trace:

```
>>> ak.sum(t, axis=1)
Traceback (most recent call last):
  File "/home/jpivarski/irishep/awkward/src/awkward/_dispatch.py", line 43, in dispatch
    next(gen_or_result)
  File "/home/jpivarski/irishep/awkward/src/awkward/operations/ak_sum.py", line 204, in sum
    return _impl(array, axis, keepdims, mask_identity, highlevel, behavior)
  File "/home/jpivarski/irishep/awkward/src/awkward/operations/ak_sum.py", line 267, in _impl
    out = ak._do.reduce(
  File "/home/jpivarski/irishep/awkward/src/awkward/_do.py", line 336, in reduce
    next = layout._reduce_next(
  File "/home/jpivarski/irishep/awkward/src/awkward/contents/regulararray.py", line 1094, in _reduce_next
    assert nextlen == 0
  File "/home/jpivarski/irishep/awkward/src/awkward/_nplikes/shape.py", line 74, in __eq__
    raise TypeError("cannot compare unknown lengths against known values")
TypeError: cannot compare unknown lengths against known values
```

The line where it fails is

https://github.com/scikit-hep/awkward/blob/ce63bf2b4afebd93e5b1b67d9985d66b51d37bc5/src/awkward/contents/regulararray.py#L1094

I suppose it would be okay for this assertion to test "unknown or zero." I'll open a PR, just trying it, and I'll ask you to test it to see if it works or if it hits another error later.
