### ISSUE TITLE
Typetracer can't slice with `(int, str, int)`

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#2764]
### Version of Awkward Array

HEAD

### Description and code to reproduce

This is either a bug in Tiled's implementation of Awkward slices or in Awkward, but from the error message, I think it's Awkward.

With an `array` that has `RecordType(ListType(RecordType(...))`, I can't slice

```python
array[0, "field_name", 0]
```

without getting

```
Traceback (most recent call last):
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/awkward/highlevel.py", line 1014, in __getitem__
    prepare_layout(self._layout[where]), self._behavior, allow_other=True
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/awkward/contents/content.py", line 519, in __getitem__
    return self._getitem(where)
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/awkward/contents/content.py", line 569, in _getitem
    return out._getitem_at(0)
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/awkward/contents/indexedarray.py", line 277, in _getitem_at
    return self._content._getitem_at(where)
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/awkward/contents/recordarray.py", line 447, in _getitem_at
    raise ak._errors.index_error(self, where)
IndexError: cannot slice RecordArray (of length 0) with 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/tiled/tiled/client/awkward.py", line 55, in __getitem__
    return self.read(slice=slice)
  File "/home/jpivarski/irishep/tiled/tiled/client/awkward.py", line 33, in read
    awkward.typetracer.touch_data(proxy_array[slice])
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/awkward/highlevel.py", line 1012, in __getitem__
    with ak._errors.SlicingErrorContext(self, where):
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/awkward/_errors.py", line 67, in __exit__
    self.handle_exception(exception_type, exception_value)
  File "/home/jpivarski/mambaforge/envs/tiled/lib/python3.10/site-packages/awkward/_errors.py", line 82, in handle_exception
    raise self.decorate_exception(cls, exception)
IndexError: cannot slice RecordArray (of length 0) with 0

This error occurred while attempting to slice

    <Array-typetracer [...] type='## * {offsets: var * int64, file: var * {...'>

with

    (0, 'era', 0)
```

My work-around is https://github.com/jpivarski/tiled-uproot/pull/3/commits/586f3c565e8ed85eccd3d8891a71c270a96616f7.

The real `RecordArray` doesn't have length zero (or the work-around wouldn't work). Could this be a case in which an effect on a Form is computed by converting it to a length-0 array, then converting back? (If so, it will eventually get us in the Dask world, too.)

Cc: @danielballan

**Comment by agoose77** [comment]
I'm AFK at the moment, but I took a look at the typetracer pathway. Our default parameters for this call 
```python
ak.typetracer.typetracer_from_form( 
    ak.forms.from_type(
        ak.types.from_datashape(
            "{x: var * {y:int64}}", 
        highlevel=False
        )
    )
)
```

produces a layout containing a length zero record array.

I'm pretty sure that we've just missed this part of the length metadata when dropping length information.

It looks like the parent layout doesn't recursively drop length information: https://github.com/scikit-hep/awkward/blob/main/src/awkward/contents/listoffsetarray.py#L214

I think we probably want a literal argument for this: `length_policy: Literal["keep", "drop_outer", "drop_recursive"]`
