### ISSUE TITLE
`argsort` fails with `RunTimeError` when processing awkward array

### ISSUE THREAD

**Issue by gordonwatts** [scikit-hep/awkward#523]
The following code:

```
import pickle
import awkward1 as ak
with open('arg_sort_boom.pcl', 'rb') as f:
    data = pickle.load(f)
    
    ak.argsort(data, axis=1)
```

Produces the following output:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-8d8e8752b65b> in <module>
      4     data = pickle.load(f)
      5 
----> 6     ak.argsort(data, axis=1)

/opt/conda/lib/python3.7/site-packages/awkward1/operations/structure.py in argsort(array, axis, ascending, stable, highlevel)
   1130         array, allow_record=False, allow_other=False
   1131     )
-> 1132     out = layout.argsort(axis, ascending, stable)
   1133     if highlevel:
   1134         return awkward1._util.wrap(out, awkward1._util.behaviorof(array))

RuntimeError: argsort_next with unbranching depth > negaxis is only expected to return RegularArray or ListOffsetArray64; instead, it returned IndexedOptionArray64

(https://github.com/scikit-hep/awkward-1.0/blob/0.4.3/src/libawkward/array/IndexedArray.cpp#L2311)
```

See [arg_sort_boom.zip](https://github.com/scikit-hep/awkward-1.0/files/5506878/arg_sort_boom.zip) for the data file. 

For completeness, the `print(data)` returns:

```
[[149, 115, 73.5, 49.1, 44.1, 40.8], [151, 94.8]]
```

and the representation:

```
<Array [[149, 115, 73.5, 49.1, ... [151, 94.8]] type='2 * option[var * ?float64]'>
```

Note that:

```
ak.argsort(ak.Array([[149, 115, 73.5, 49.1, 44.1, 40.8], [151, 94.8]]), axis=1)
```

returns the expected answer:

```
Array [[5, 4, 3, 2, 1, 0], [1, 0]] type='2 * var * int64'>​
```

So something is bad about the array that I'm using as input. Comments about the array:

- It was loaded from standard ROOT files using `uproot4` into an `awkward1` array.
- It was then saved to a parquet file using `ak.to_parquet`
- It was then loaded from the parquet file using `ak.from_parquet`.
- The type, `?float54` might be a clue here.

**Comment by gordonwatts** [comment]
As a workaround first do `ak.fill_none(data, [0])` and `argsort` will work properly. That may also tell you what is going wrong above.

**Comment by ianna** [comment]
thanks, @gordonwatts ! I managed to reproduce the error:
```python
    def test_gordons_test():
        array = awkward1.Array([[149, 115, 73.5, 49.1, 44.1, 40.8], [151, 94.8]]).layout
        assert awkward1.to_list(array.argsort(1, True, False)) == [[5, 4, 3, 2, 1, 0], [1, 0]]
        with open('arg_sort_boom.pcl', 'rb') as f:
            data = pickle.load(f)
    
>           assert awkward1.to_list(awkward1.argsort(data, axis=1)) == [[5, 4, 3, 2, 1, 0], [1, 0]]

tests/test_0074-argsort-and-sort.py:19: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

array = <Array [[149, 115, 73.5, 49.1, ... [151, 94.8]] type='2 * option[var * ?float64]'>, axis = 1, ascending = True, stable = True, highlevel = True

    @awkward1._connect._numpy.implements("argsort")
    def argsort(array, axis=-1, ascending=True, stable=True, highlevel=True):
        """
        Args:
            array: Data for which to get a sorting index, possibly within nested
                lists.
            axis (int): The dimension at which this operation is applied. The
                outermost dimension is `0`, followed by `1`, etc., and negative
                values count backward from the innermost: `-1` is the innermost
                dimension, `-2` is the next level up, etc.
            ascending (bool): If True, the first value in each sorted group
                will be smallest, the last value largest; if False, the order
                is from largest to smallest.
            stable (bool): If True, use a stable sorting algorithm (introsort:
                a hybrid of quicksort, heapsort, and insertion sort); if False,
                use a sorting algorithm that is not guaranteed to be stable
                (heapsort).
            highlevel (bool): If True, return an #ak.Array; otherwise, return
                a low-level #ak.layout.Content subclass.
    
        For example,
    
            >>> ak.argsort(ak.Array([[7.7, 5.5, 7.7], [], [2.2], [8.8, 2.2]]))
            <Array [[1, 0, 2], [], [0], [1, 0]] type='4 * var * int64'>
    
        The result of this function can be used to index other arrays with the
        same shape:
    
            >>> data = ak.Array([[7, 5, 7], [], [2], [8, 2]])
            >>> index = ak.argsort(index)
            >>> index
            <Array [[1, 0, 2], [], [0], [1, 0]] type='4 * var * int64'>
            >>> data[index]
            <Array [[5, 7, 7], [], [2], [2, 8]] type='4 * var * int64'>
        """
        layout = awkward1.operations.convert.to_layout(
            array, allow_record=False, allow_other=False
        )
>       out = layout.argsort(axis, ascending, stable)
E       RuntimeError: argsort_next with unbranching depth > negaxis is only expected to return RegularArray or ListOffsetArray64; instead, it returned IndexedOptionArray64
E       
E       (https://github.com/scikit-hep/awkward-1.0/blob/0.4.4/src/libawkward/array/IndexedArray.cpp#L2311)

awkward1/operations/structure.py:1247: RuntimeError

```

**Comment by ianna** [comment]
@jpivarski - it looks like the `argsort_next` produces a correct output here:
https://github.com/scikit-hep/awkward-1.0/blob/c3b9442644004784d81fbdd3cde577a528ada93e/src/libawkward/array/IndexedArray.cpp#L2264
then it should have bailed out here, but didn't due to a `branchdepth.second` :
https://github.com/scikit-hep/awkward-1.0/blob/c3b9442644004784d81fbdd3cde577a528ada93e/src/libawkward/array/IndexedArray.cpp#L2271

**Comment by jpivarski** [comment]
The key thing is that `ak.argsort` isn't handling IndexedOptionArray (which allows for the _possibility_ of None; that's why `ak.fill_none` is a work-around: you didn't have any None values, but you had the structure that would allows for it).

For example, this works:

```python
>>> ak.argsort(ak.Array([[3, 2, 1], [], [4, 5]]), axis=1)
<Array [[2, 1, 0], [], [0, 1]] type='3 * var * int64'>
```

but this does not work:

```python
>>> ak.argsort(ak.Array([[3, 2, 1], [], None, [4, 5]]), axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/awkward-1.0/awkward1/operations/structure.py", line 1247, in argsort
    out = layout.argsort(axis, ascending, stable)
RuntimeError: argsort_next with unbranching depth > negaxis is only expected to return RegularArray or ListOffsetArray64; instead, it returned IndexedOptionArray64
```

It doesn't matter that there's a None in the data; we could put it at the end and slice it off, yet have the same problem:

```python
>>> ak.argsort(ak.Array([[3, 2, 1], [], [4, 5], None])[:-1], axis=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/awkward-1.0/awkward1/operations/structure.py", line 1247, in argsort
    out = layout.argsort(axis, ascending, stable)
RuntimeError: argsort_next with unbranching depth > negaxis is only expected to return RegularArray or ListOffsetArray64; instead, it returned IndexedOptionArray64
```

And that's because an array that could have a None in it has a different layout:

```python
>>> ak.Array([[3, 2, 1], [], [4, 5], None])[:-1].layout
<IndexedOptionArray64>
    <index><Index64 i="[0 1 2]" offset="0" length="3" at="0x55badd956480"/></index>
    <content><ListOffsetArray64>
        <offsets><Index64 i="[0 3 3 5]" offset="0" length="4" at="0x55badd952460"/></offsets>
        <content><NumpyArray format="l" shape="5" data="3 2 1 4 5" at="0x55badd954470"/></content>
    </ListOffsetArray64></content>
</IndexedOptionArray64>
```

than an array that cannot have a None in it:

```python
>>> ak.Array([[3, 2, 1], [], [4, 5]]).layout
<ListOffsetArray64>
    <offsets><Index64 i="[0 3 3 5]" offset="0" length="4" at="0x55badd958490"/></offsets>
    <content><NumpyArray format="l" shape="5" data="3 2 1 4 5" at="0x55badd95a4a0"/></content>
</ListOffsetArray64>
```

(IndexedOptionArray64 vs ListOffsetArray64). The `ak.argsort` operation is missing a handler for the IndexedOptionArray64 case, and the internal RuntimeError is saying that this assumption is not satisfied.

I'm going to try PR #524 now.

**Comment by ianna** [comment]
I think, this can be closed now.

**Comment by jpivarski** [comment]
That's right. (I thought it was linked to the PR.)
