### ISSUE TITLE
Median

### ISSUE THREAD

**Issue by mariogeiger** [scikit-hep/awkward#741]
Hi :-)

# Aim
I would like to compute the median

# What I tried
I guess I should be able to do it using a combination of `ak.sort` and `ak.num` but I don't manage to do the indexing

**Comment by jpivarski** [comment]
Median is different from mean, variance, covariances, and even linear fits in that it can't be computed from a small (non-growing) set of numbers. That's what everything in `ak.operations.reducers.*` have in common. However, this property is only really necessary for parallelizing a calculation, and that's not what you get when you call `ak.mean`, `ak.var`, etc., so maybe median _does_ belong in that set.

If you're computing a median at `axis=0`, i.e. you have a one-dimensional array and you want to get a scalar result for the median, just pass it into the NumPy function, [np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html), possibly wrapping the Awkward Array with [np.asarray](https://numpy.org/doc/stable/reference/generated/numpy.asarray.html) so that NumPy recognizes it as an array. (We're going to find a way to fix that: #630.)

For computing a median at `axis=1`, I've worked out how you can do it below. After going through it, I can totally sympathize that you had trouble with it! This case is tricky for a number of reasons, and so "median" should probably become a library function.

First, start with a small, synthetic example of what we want to solve. Here's an array with variable-length lists at `axis=1`, some of which are empty (so that the solution has to deal with that).

```python
array = ak.Array([[2.2, 1.1, 0.0], [], [3.3, 4.4], [5.5], [8.8, 6.6, 7.7, 9.9]])
```

You're right that the first thing we want to do is sort within each list (i.e. in `axis=1`).

```python
>>> sorted_array = ak.sort(array, axis=1)
>>> sorted_array.tolist()
[[0.0, 1.1, 2.2], [], [3.3, 4.4], [5.5], [6.6, 7.7, 8.8, 9.9]]
```

We'll see in a moment that the empty list is going to be a problem. We'll want to find the two indexes that pick out the element or two elements that are closest to the center of each list, but the empty list has no indexes that can pick out an element. So we'll keep on hand a version of the `sorted_array` that doesn't have any empty lists, replacing them with `None` as a placeholder so that it doesn't further complicate the indexing (that is, every list stays _where_ it is, unaffected by the removal of the empties). The [ak.mask](https://awkward-array.readthedocs.io/en/latest/_auto/ak.mask.html) function does this, but it has a shorthand syntax through `.mask[·]`.

```python
>>> sorted_without_empties = sorted_array.mask[ak.num(sorted_array) != 0]
>>> sorted_without_empties.tolist()
[[0.0, 1.1, 2.2], None, [3.3, 4.4], [5.5], [6.6, 7.7, 8.8, 9.9]]
```

Now: on with the indexing. To compute a median, we want to average the element at `floor((N - 1) / 2)` and `ceil((N - 1) / 2)`, where `N` is the length of each list. If `N` is even, these are the two elements that are equally close to the middle; if `N` is odd, these are both the same element, exactly in the middle. (Averaging a single number with itself returns itself, so we don't need to introduce an "if" statement, or [ak.where](https://awkward-array.readthedocs.io/en/latest/_auto/ak.where.html) to handle both even and odd.)

We can do that, starting with [ak.num](https://awkward-array.readthedocs.io/en/latest/_auto/ak.num.html):

```python
>>> ak.num(sorted_array, axis=1)
<Array [3, 0, 2, 1, 4] type='5 * int64'>
>>> np.floor((ak.num(sorted_array, axis=1) - 1) / 2)
<Array [1, -1, 0, 0, 1] type='5 * float64'>
>>> np.ceil((ak.num(sorted_array, axis=1) - 1) / 2)
<Array [1, -0, 1, 0, 2] type='5 * float64'>
```

(and you can already see how the indexes for the empty list, `-1` and `-0`, are nonsensical). Although these values are, by construction, integers, they have floating point type and have to be converted to true integers. There's [ak.values_astype](https://awkward-array.readthedocs.io/en/latest/_auto/ak.values_astype.html) for that.

```python
>>> low_index = ak.values_astype(np.floor((ak.num(sorted_array, axis=1) - 1) / 2), np.int64)
>>> high_index = ak.values_astype(np.ceil((ak.num(sorted_array, axis=1) - 1) / 2), np.int64)
>>> low_index, high_index
(<Array [1, -1, 0, 0, 1] type='5 * int64'>,
 <Array [1, 0, 1, 0, 2] type='5 * int64'>)
```

Now we're _still_ not there because these indexes should apply to the second (jagged) dimension, but here they are in the first dimension, as flat arrays. If you try to just slice with this, it will be trying to find the _list_ at index `1`, then the _list_ at index `-1`, etc.

```python
>>> sorted_without_empties[low_index].tolist()
[None, [6.6, 7.7, 8.8, 9.9], [0.0, 1.1, 2.2], [0.0, 1.1, 2.2], None]
```

There's no error there, but it's not at all what we want. It seems like you ought to be able to do a slice like `[:, low_index]`, but that means requesting indexes `1`, `-1`, `0`, `0`, `1` from _every_ list.

```python
>>> sorted_without_empties[:, low_index]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/miniconda3/lib/python3.8/site-packages/awkward/highlevel.py", line 1007, in __getitem__
    return ak._util.wrap(self._layout[where], self._behavior)
ValueError: in ListArray64 attempting to get 1, index out of range
```

That's also not what we want to do (even if it were possible): we want to get `1` from the _first_ list, skip `-1` (because that's `None`), `0` from the _third_ list, etc. For that, we need the `low_index` and `high_index` to be jagged arrays of integers with the same lengths at all dimensions but the innermost one. It has to be shaped like `[[1], [-1], [0], [0], [1]]`. NumPy's `np.newaxis` does that:

```python
>>> low_index[:, np.newaxis]
<Array [[1], [-1], [0], [0], [1]] type='5 * 1 * int64'>
```

though it's going to be relevant that this inner dimension has fixed-length 1, rather than a variable length that happens to be 1. Arrays with fixed-length dimensions have to reproduce what NumPy does, which often isn't what we want, so some behaviors hinge on whether a dimension is fixed-length or variable length. For instance, NumPy says that fixed-length dimensions should be broadcasted to the length of the other dimension, which is useful in some cases:

```python
>>> sorted_without_empties[low_index[:, np.newaxis]].tolist()
[[None], [[6.6, 7.7, 8.8, 9.9]], [[0.0, 1.1, 2.2]], [[0.0, 1.1, 2.2]], [None]]
```

but not ours. Since the behaviors depend on fixed-length versus variable-length dimensions, there are functions for converting between them: [ak.to_regular](https://awkward-array.readthedocs.io/en/latest/_auto/ak.to_regular.html) and [ak.from_regular](https://awkward-array.readthedocs.io/en/latest/_auto/ak.from_regular.html).

```python
>>> ak.from_regular(low_index[:, np.newaxis])
<Array [[1], [-1], [0], [0], [1]] type='5 * var * int64'>
```

This one does exactly what we want.

```python
>>> sorted_without_empties[ak.from_regular(low_index[:, np.newaxis])].tolist()
[[1.1], None, [3.3], [5.5], [7.7]]
```

Now we can get the low and high values in each list.

```python
>>> low = sorted_without_empties[ak.from_regular(low_index[:, np.newaxis])]
>>> high = sorted_without_empties[ak.from_regular(high_index[:, np.newaxis])]
>>> low, high
(<Array [[1.1], None, [3.3], [5.5], [7.7]] type='5 * option[var * float64]'>,
 <Array [[1.1], None, [4.4], [5.5], [8.8]] type='5 * option[var * float64]'>)
```

The median is the average of these two.

```python
>>> (low + high) / 2
<Array [[1.1], None, [3.85], [5.5], [8.25]] type='5 * option[var * float64]'>
```

Or, actually, it's the first element of each of these.

```python
>>> ((low + high) / 2)[:, 0]
<Array [1.1, None, 3.85, 5.5, 8.25] type='5 * ?float64'>
```

Whew! Given how much work this was, it should be wrapped up as a library function, though it would need to be generalized to apply to any `axis` (by making slices with `slice(None) * ndim + (np.newaxis,)`, rather than `:, np.newaxis`, etc.). All of the other functions in `ak.operations.reducers.*` can handle weights. I'm not really sure what to do with weights in a median...

**Comment by mariogeiger** [comment]
Thanks for the complete explanation of how to do the indexing properly!

**Comment by jpivarski** [comment]
Closed in favor of #3289. We should do all three functions (with one implementation).

**Comment by NicoWeio** [comment]
For anyone who just wants a working (though still limited to `axis=1`) function to drop into their project, I “vibe-coded” one based on the explanation given by @jpivarski (thanks!).

```python
def ak_median_axis1(array: ak.Array) -> ak.Array:
    # Sort each sublist along axis=1
    sorted_array = ak.sort(array, axis=1)

    # Mask out empty sublists (to preserve structure with None placeholders)
    nonempty_mask = ak.num(sorted_array, axis=1) != 0
    sorted_no_empty = sorted_array.mask[nonempty_mask]

    # Compute counts per sublist
    counts = ak.num(sorted_array, axis=1)

    # Compute low and high indices for median
    low_index = ak.values_astype(np.floor((counts - 1) / 2), np.int64)
    high_index = ak.values_astype(np.ceil((counts - 1) / 2), np.int64)

    # Convert index arrays to jagged form for per-sublist indexing
    low_jagged = ak.from_regular(low_index[:, np.newaxis])
    high_jagged = ak.from_regular(high_index[:, np.newaxis])

    # Gather low and high values from each non-empty sublist
    low_values = sorted_no_empty[low_jagged]
    high_values = sorted_no_empty[high_jagged]

    # Compute median (average of low and high)
    median_pair = (low_values + high_values) / 2

    # Extract the scalar from each length-1 list
    return median_pair[:, 0]
```

<details>
<summary>And here's a function for quantiles</summary>

```python
def ak_quantile_axis1(array: ak.Array, q: float) -> ak.Array:
    """
    Compute the q‑th quantile of a jagged Awkward Array along axis=1.

    Parameters
    ----------
    array : ak.Array
        A one-dimensional JaggedArray at axis=1.
    q : float
        Quantile in [0, 1].

    Returns
    -------
    ak.Array
        An array of q‑th quantiles (float or None) for each sublist.
    """
    # sort each sublist
    sorted_array = ak.sort(array, axis=1)

    # counts per sublist
    counts = ak.num(sorted_array, axis=1)

    # mask out empty sublists
    nonempty = counts != 0
    sorted_ne = sorted_array.mask[nonempty]

    # compute real index = (n-1)*q
    real_idx = (counts - 1) * q
    low_idx = ak.values_astype(np.floor(real_idx), np.int64)
    high_idx = ak.values_astype(np.ceil(real_idx), np.int64)
    frac = real_idx - low_idx

    # build jagged indices
    low_j = ak.from_regular(low_idx[:, np.newaxis])
    high_j = ak.from_regular(high_idx[:, np.newaxis])

    # gather values
    low_vals = sorted_ne[low_j]
    high_vals = sorted_ne[high_j]

    # interpolate
    quant = low_vals + frac[:, np.newaxis] * (high_vals - low_vals)

    # extract scalar and return (skipping empties)
    return quant[:, 0]
```
</details>

PS: Contrary to the last message by @jpivarski, neither this nor #3289 is closed.

**Comment by ianna** [comment]
@NicoWeio - Thanks! As a start it looks great! You are welcome to contribute it to the repo :-)

**Comment by NicoWeio** [comment]
I'd love to! 🚀
How should (so far) invalid axes be handled? `NotImplementedError`?
Because I don't think I'll manage to generalize it myself, at least quickly: I only started using _awkward_ yesterday. :)

**Comment by ikrommyd** [comment]
> I'd love to! 🚀 How should (so far) invalid axes be handled? `NotImplementedError`? Because I don't think I'll manage to generalize it myself, at least quickly: I only started using _awkward_ yesterday. :)

Feel free to take a look at the other statistical functions implementations. All the high level functions that the user sees are in `src/awkward/operations` 😃
