### ISSUE TITLE
Buggy behavior in ak.num() on TTrees

### ISSUE THREAD

**Issue by masonproffitt** [scikit-hep/awkward#756]
Not sure whether this should be an issue in uproot or awkward. `ak.num()` doesn't work with `uproot.lazy()`:

```python
>>> import uproot
>>> import awkward as ak
>>> uproot.__version__
'4.0.4'
>>> ak.__version__
'1.1.2'
>>> uproot.lazy('file.root')
<Array [{int_branch: 0, ... bool_branch: True}] type='2 * {"int_branch": int32, ...'>
>>> ak.num(uproot.lazy('file.root'), axis=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/iris-hep/lib/python3.9/site-packages/awkward/operations/structure.py", line 256, in num
    out = layout.num(axis=axis)
  File "/home/user/miniconda3/envs/iris-hep/lib/python3.9/site-packages/awkward/partition.py", line 481, in num
    return sum(x.num(axis) for x in self.partitions)
TypeError: unsupported operand type(s) for +: 'int' and 'awkward._ext.Record'
```

Note that you can apply `ak.num()` to a TTree in other ways, albeit with inconsistent results:

```python
>>> ak.num(uproot.open('file.root')['tree'], axis=0)
5
```
(there are five branches)

```python
>>> ak.num(uproot.open('file.root')['tree'].arrays(), axis=0)
<Record ... double_branch: 2, bool_branch: 2} type='{"int_branch": int64, "long_...'>
```
(there are two entries in each branch)

Intuitively I would have expected all of the above options to give me just `2`.

**Comment by jpivarski** [comment]
PR #757 fixes `ak.num` with `axis=0` on PartitionedArrays (that was how lazy arrays are relevant, so it is an Awkward thing).

As for this case:

> Note that you can apply `ak.num()` to a TTree in other ways, albeit with inconsistent results:
> 
> ```python
> >>> ak.num(uproot.open('file.root')['tree'], axis=0)
> 5
> ```
> 
> (there are five branches)

A TTree is not an array. It is iterable, but that's for finding its branches, not its data as an array.

```python
>>> import uproot, skhep_testdata
>>> tree = uproot.open(skhep_testdata.data_path("uproot-Zmumu.root") + ":events")
>>> list(tree)
[<TBranch 'Type' at 0x7f536ff9b2b0>,
 <TBranch 'Run' at 0x7f536ff9bb50>,
 <TBranch 'Event' at 0x7f536ff30190>,
 <TBranch 'E1' at 0x7f536ff308b0>,
 <TBranch 'px1' at 0x7f536ff30fd0>,
 <TBranch 'py1' at 0x7f536ff35730>,
 <TBranch 'pz1' at 0x7f536ff35e50>,
 <TBranch 'pt1' at 0x7f536ff375b0>,
 <TBranch 'eta1' at 0x7f536ff37cd0>,
 <TBranch 'phi1' at 0x7f536ff3c430>,
 <TBranch 'Q1' at 0x7f536ff3cb50>,
 <TBranch 'E2' at 0x7f536ff3f2b0>,
 <TBranch 'px2' at 0x7f536ff3f9d0>,
 <TBranch 'py2' at 0x7f536ff43130>,
 <TBranch 'pz2' at 0x7f536ff43850>,
 <TBranch 'pt2' at 0x7f536ff43f70>,
 <TBranch 'eta2' at 0x7f536ff466d0>,
 <TBranch 'phi2' at 0x7f536ff46df0>,
 <TBranch 'Q2' at 0x7f536ff49550>,
 <TBranch 'M' at 0x7f536ff49c70>]
```

All of the Awkward functions fall back on iterating over their inputs, which in this case, has 20 items.
