### ISSUE TITLE
ak.cartesian fails on empty lists of union types

### ISSUE THREAD

**Issue by lgray** [scikit-hep/awkward#805]
Awkward version = 1.2.0

```python3
import awkward as ak

muon = ak.Array([[{"pt": 1.}],[]], with_name="muon")
electron = ak.Array([[],[{"pt": 1.}]], with_name="electron")

muon = muon[muon.pt > 5]
electron = electron[electron.pt > 5]

leptons = ak.concatenate([muon,electron], axis=1)
candidate = ak.firsts(leptons)

ak.cartesian([candidate, candidate])
```

fails with:
```
Traceback (most recent call last):
  File "make_example.py", line 12, in <module>
    prod = ak.cartesian([candidate,candidate])
  File "/opt/conda/lib/python3.8/site-packages/awkward/operations/structure.py", line 3089, in cartesian
    out = ak._util.broadcast_and_apply(
  File "/opt/conda/lib/python3.8/site-packages/awkward/_util.py", line 1037, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0, user)
  File "/opt/conda/lib/python3.8/site-packages/awkward/_util.py", line 799, in apply
    outcontent = apply(nextinputs, depth + 1, user)
  File "/opt/conda/lib/python3.8/site-packages/awkward/_util.py", line 752, in apply
    outcontent = apply(nextinputs, depth, user)
  File "/opt/conda/lib/python3.8/site-packages/awkward/_util.py", line 717, in apply
    for i in range(numoutputs)
UnboundLocalError: local variable 'numoutputs' referenced before assignment
```

and indeed numoutputs is not defined in the case there are no unique non-null entries.

**Comment by ianna** [comment]
@lgray - it works if an `axis=0` argument is given to `ak.cartesian`:
```python
    muon = ak.Array([[{"pt": 1.}],[]], with_name="muon")
    electron = ak.Array([[],[{"pt": 1.}]], with_name="electron")

    muon = muon[muon.pt > 5]
    electron = electron[electron.pt > 5]

    leptons = ak.concatenate([muon,electron], axis=1)
    candidate = ak.firsts(leptons)
    assert ak.to_list(ak.Array(candidate)) == [ None, None ]

    result = ak.cartesian([candidate, candidate], axis=0)
    assert ak.to_list(result) == [(None, None), (None, None), (None, None), (None, None)]

```
I'm not sure if `ak.cartesian` needs to check on an empty input and (re-)set its axis? @jpivarski ?

**Comment by ianna** [comment]
@lgray and @jpivarski - The default `axis` for `ak.cartesian` is `1`. Perhaps,  a `ValueError` message such as in https://github.com/scikit-hep/awkward-1.0/pull/808 be sufficient? Thanks.

**Comment by jpivarski** [comment]
`axis=0` follows a different code path, and the error

```
local variable 'numoutputs' referenced before assignment
```

it's about Python taking an unexpected code path. If the operation is invalid, then catching it with a ValueError would be appropriate. Did this array have 1 dimension? If so, then yes, `axis != 0` should be an error. It's just hitting a programming logic error before discovering that.

**Comment by ianna** [comment]
`axis=1` is valid for the actual arrays, but they appear as if they were empty:
```python
<IndexedOptionArray64>
    <index><Index64 i="[-1 -1]" offset="0" length="2" at="0x7f8d7d4fdbb0"/></index>
    <content><UnionArray8_64>
        <tags><Index8 i="[]" offset="0" length="0" at="0x000000000000"/></tags>
        <index><Index64 i="[]" offset="0" length="0" at="0x000000000000"/></index>
        <content tag="0">
            <IndexedArray64>
                <index><Index64 i="[]" offset="0" length="0" at="0x000000000000"/></index>
                <content><RecordArray length="1">
                    <parameters>
                        <param key="__record__">"muon"</param>
                    </parameters>
                    <field index="0" key="pt">
                        <NumpyArray format="d" shape="1" data="1" at="0x7f8d7d90d400"/>
                    </field>
                </RecordArray></content>
            </IndexedArray64>
        </content>
        <content tag="1">
            <IndexedArray64>
                <index><Index64 i="[]" offset="0" length="0" at="0x000000000000"/></index>
                <content><RecordArray length="1">
                    <parameters>
                        <param key="__record__">"electron"</param>
                    </parameters>
                    <field index="0" key="pt">
                        <NumpyArray format="d" shape="1" data="1" at="0x7f8d7d898c00"/>
                    </field>
                </RecordArray></content>
            </IndexedArray64>
        </content>
    </UnionArray8_64></content>
</IndexedOptionArray64>
<IndexedOptionArray64>
    <index><Index64 i="[-1 -1]" offset="0" length="2" at="0x7f8d7d4fdbb0"/></index>
    <content><UnionArray8_64>
        <tags><Index8 i="[]" offset="0" length="0" at="0x000000000000"/></tags>
        <index><Index64 i="[]" offset="0" length="0" at="0x000000000000"/></index>
        <content tag="0">
            <IndexedArray64>
                <index><Index64 i="[]" offset="0" length="0" at="0x000000000000"/></index>
                <content><RecordArray length="1">
                    <parameters>
                        <param key="__record__">"muon"</param>
                    </parameters>
                    <field index="0" key="pt">
                        <NumpyArray format="d" shape="1" data="1" at="0x7f8d7d90d400"/>
                    </field>
                </RecordArray></content>
            </IndexedArray64>
        </content>
        <content tag="1">
            <IndexedArray64>
                <index><Index64 i="[]" offset="0" length="0" at="0x000000000000"/></index>
                <content><RecordArray length="1">
                    <parameters>
                        <param key="__record__">"electron"</param>
                    </parameters>
                    <field index="0" key="pt">
                        <NumpyArray format="d" shape="1" data="1" at="0x7f8d7d898c00"/>
                    </field>
                </RecordArray></content>
            </IndexedArray64>
        </content>
    </UnionArray8_64></content>
</IndexedOptionArray64>
```

**Comment by jpivarski** [comment]
As long as it has the right number of dimensions, empty arrays should be allowed, though the result of the operation might be empty.

The array that @lgray is trying to `ak.cartesian` is one-dimensional:

```python
>>> candidate
<Array [None, None] type='2 * ?union[muon["pt": float64], electron["pt": float64]]'>
>>> ak.cartesian([candidate, candidate])
# ... (fails)
```

With the default `axis=1`, `ak.cartesian` _should_ fail for one-dimensional arrays:

```python
>>> simpler = ak.Array([1, 2, 3])
>>> ak.cartesian([simpler, simpler])
# ... (also fails, as it should, though the error message could be more clear
```

(Note: the error message is the same for `simpler = ak.Array([None, None])`, as it should be, though again it could be clearer.)

Although the "referenced before assignment" error is a programming error (the sort of thing a static type checker would catch, actually), it does fail on the cases that are supposed to fail and succeeds on the cases that are supposed to succeed. @ianna, you showed that it works when `axis=0`, as a one-dimensional array should, and if I change `candidate` into a two-dimensional array, it also works:

```python
>>> candidate[np.newaxis]
<Array [[None, None]] type='1 * 2 * ?union[muon["pt": float64], electron["pt": f...'>
>>> ak.cartesian([candidate[np.newaxis], candidate[np.newaxis]])
<Array [... ), (None, None), (None, None)]] type='1 * var * (?union[muon["pt": f...'>
```

So that unconsidered code path _and_ the unclear error message could both be fixed by an up-front check that throws a good error message. Just before

https://github.com/scikit-hep/awkward-1.0/blob/1492c4906df9f5bbf7b4f244de543188563015a4/src/awkward/operations/structure.py#L2897

there could be a check to ensure that `posaxis` (the `axis` parameter after negative-value handling) is in the correct range for the `purelist_depth` of all the arguments. (The arguments can have different depths from each other, but the chosen `posaxis` has to exist for all of them.) Doing this would get `ak.argcartesian` for free, because it's defined in terms of `ak.cartesian`.

**Comment by lgray** [comment]
@ianna @jpivarski 

Unfortunately #808 is not the solution to this problem, especially since the arrays are the exact same form in a passing case vs. a failing case.

The two arrays I am trying to cross in the full data look like:
```
[[FatJet], [FatJet], [FatJet], [FatJet], [], ... [], [], [], [], [FatJet], [], []]
[None, None, None, None, None, None, None, ... None, None, None, None, None, None]
```
where the first is a non-option list record array, and the second is an option union record array.
axis = 1 here should always be viable since the second broadcasts into the first.

The error occurs when the second is all "Nones".
This appears to extend to the case where any of the input arrays to the cartesian product are all Nones?

Here's a better minimal example.

```python3
import awkward as ak

def mre(lepcut=6., jetcut=1.5):
    muon = ak.Array([[{"pt": 1.}],[]], with_name="muon")
    electron = ak.Array([[],[{"pt": 5.}]], with_name="electron")

    muon = muon[muon.pt > lepcut]
    electron = electron[electron.pt > lepcut]

    jet = ak.Array([[{"pt": 2.0}],[{"pt":4.0}]])
    jet = jet[jet.pt > jetcut]

    leptons = ak.concatenate([muon,electron], axis=1)
    candidate = ak.firsts(leptons)

    x = ak.cartesian([candidate, jet])
    print(x)

if __name__ == "__main__":
    mre(2.5, 1.5)
    mre()
```

which outputs with awkward 1.2.1:
```
[None, [({pt: 5}, {pt: 4})]]
Traceback (most recent call last):
  File "mre.py", line 21, in <module>
    mre()
  File "mre.py", line 16, in mre
    x = ak.cartesian([candidate, jet])
  File "/Users/lagray/miniconda3/envs/coffea-jetmet/lib/python3.7/site-packages/awkward/operations/structure.py", line 3090, in cartesian
    layouts, getfunction3, behavior, right_broadcast=False, pass_depth=True
  File "/Users/lagray/miniconda3/envs/coffea-jetmet/lib/python3.7/site-packages/awkward/_util.py", line 1037, in broadcast_and_apply
    out = apply(broadcast_pack(inputs, isscalar), 0, user)
  File "/Users/lagray/miniconda3/envs/coffea-jetmet/lib/python3.7/site-packages/awkward/_util.py", line 799, in apply
    outcontent = apply(nextinputs, depth + 1, user)
  File "/Users/lagray/miniconda3/envs/coffea-jetmet/lib/python3.7/site-packages/awkward/_util.py", line 752, in apply
    outcontent = apply(nextinputs, depth, user)
  File "/Users/lagray/miniconda3/envs/coffea-jetmet/lib/python3.7/site-packages/awkward/_util.py", line 717, in apply
    for i in range(numoutputs)
UnboundLocalError: local variable 'numoutputs' referenced before assignment
```

**Comment by jpivarski** [comment]
> The two arrays I am trying to cross in the full data look like:
> 
> ```
> [[FatJet], [FatJet], [FatJet], [FatJet], [], ... [], [], [], [], [FatJet], [], []]
> [None, None, None, None, None, None, None, ... None, None, None, None, None, None]
> ```
> 
> where the first is a non-option list record array, and the second is an option union record array.
> axis = 1 here should always be viable since the second broadcasts into the first.

Okay, that's different. `axis=1` is valid because the arrays are two-dimensional after broadcasting. (Broadcasting happens during the `ak.cartesian` operation itself, as @nsmith- showed me once that Cartesian product can be implemented in terms of broadcasting, and so that's how it's implemented.)

Here are some tests with simple types of the same dimensionality:

```python
>>> one_dimensional = ak.Array([1.1, 2.2, 3.3, 4.4, 5.5])
>>> two_dimensional = ak.Array([[1], [2], [], [], [3]])
>>> ak.broadcast_arrays(one_dimensional, two_dimensional)
[<Array [[1.1], [2.2], [], [], [5.5]] type='5 * var * float64'>, <Array [[1], [2], [], [], [3]] type='5 * var * int64'>]
>>> ak.cartesian([one_dimensional, two_dimensional])
<Array [[(1.1, 1)], [(2.2, ... [], [(5.5, 3)]] type='5 * var * (float64, int64)'>

>>> none_dimensional = ak.Array([None, None, None, None, None])
>>> ak.broadcast_arrays(none_dimensional, two_dimensional)
[<Array [None, None, None, None, None] type='5 * option[var * bool]'>, <Array [None, None, None, None, None] type='5 * option[var * int64]'>]
>>> ak.cartesian([none_dimensional, two_dimensional])
<Array [None, None, None, None, None] type='5 * option[var * (bool, int64)]'>
```

So my idea of putting a general comparison of array dimension and `axis` before any processing isn't a good one, as it would exclude valid cases of one-dimensional × two-dimensional that broadcast to two-dimensional.

Going back to your `candidate`, it does fail with the UnboundLocalError when I try mix `candidate` with a simple two-dimensional array:

```python
>>> candidate
<Array [None, None] type='2 * ?union[muon["pt": float64], electron["pt": float64]]'>
>>> ak.cartesian([candidate, ak.Array([[1, 2, 3], []])])
# ...
# UnboundLocalError: local variable 'numoutputs' referenced before assignment
```

_but also,_ it fails in the same way if we try to explicitly broadcast it:

```python
>>> ak.broadcast_arrays(candidate, ak.Array([[1, 2, 3], []]))
# ...
# UnboundLocalError: local variable 'numoutputs' referenced before assignment
```

So this isn't an error with `ak.cartesian` and the fix shouldn't be in `ak.cartesian`. It's a corner case in broadcasting.
