### ISSUE TITLE
`from_parquet` does not work with file-like objects

### ISSUE THREAD

**Issue by nikoladze** [scikit-hep/awkward#921]
For example

```pycon
>>> import awkward as ak
>>> array = ak.Array([1, 2, 3])
>>> ak.to_parquet(array, "array.parquet")
>>> f = open("array.parquet", "rb")
>>> array2 = ak.from_parquet(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikolai/.local/lib/python3.9/site-packages/awkward/operations/convert.py", line 3566, in from_parquet
    single_file = pyarrow.parquet.ParquetFile(filename)
  File "/home/nikolai/.local/lib/python3.9/site-packages/pyarrow/parquet.py", line 217, in __init__
    self.reader.open(source, use_memory_map=memory_map,
  File "pyarrow/_parquet.pyx", line 947, in pyarrow._parquet.ParquetReader.open
  File "pyarrow/io.pxi", line 1473, in pyarrow.lib.get_reader
  File "pyarrow/io.pxi", line 1466, in pyarrow.lib.get_native_file
TypeError: Cannot convert bytes to pyarrow.lib.NativeFile
```

presumably because file-like objects are instances of `Iterable`, so it tries to loop over them here:

https://github.com/scikit-hep/awkward-1.0/blob/0fe77918e1fa828e539ff287153150d028decfda/src/awkward/operations/convert.py#L3616-L3617

```python
>>> import awkward as ak
>>> ak.__version__
'1.3.0'
```

**Comment by nikoladze** [comment]
Actually noticed the issue when i tried to use an http file-like object from `fsspec`, so #886 could be related

```
python -m http.server
```
```pycon
>>> import fsspec
>>> import awkward as ak
>>> of = fsspec.open("http://localhost:8000/array.parquet", "rb")
>>> f = of.open()
>>> array = ak.from_parquet(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nikolai/.local/lib/python3.9/site-packages/awkward/operations/convert.py", line 3624, in from_parquet
    single_file = pyarrow.parquet.ParquetFile(filename)
  File "/home/nikolai/.local/lib/python3.9/site-packages/pyarrow/parquet.py", line 217, in __init__
    self.reader.open(source, use_memory_map=memory_map,
  File "pyarrow/_parquet.pyx", line 947, in pyarrow._parquet.ParquetReader.open
  File "pyarrow/io.pxi", line 1473, in pyarrow.lib.get_reader
  File "pyarrow/io.pxi", line 1466, in pyarrow.lib.get_native_file
TypeError: Cannot convert bytes to pyarrow.lib.NativeFile
```

Edit: actually the python http server would not work since it does not support byte ranges, but one could spawn an nginx or similar with docker, e.g.
```
docker run --rm --name nginx -v $(pwd):/usr/share/nginx/html:ro -p 8000:80 nginx
```

**Comment by agoose77** [comment]
@nikoladze you're right that the current implementation *appears* to be unable to handle `File`-like objects due to that `Iterable` check, which was introduced in #706. 

Addressing this and #886 is going to take a little more time that I have available right now unfortunately. Is this something that you need and can't work around?

**Comment by nikoladze** [comment]
I'd like to run some tests with parquet files over http (also making use of streaming I/O, not downloading the file). For this it should be sufficient to have the file-like objects passed through correctly to `pyarrow.parquet.ParquetFile`.

**Comment by agoose77** [comment]
You can try the [`bugfix-from-parquet-file-like`](https://github.com/scikit-hep/awkward-1.0/tree/bugfix-from-parquet-file-like) branch if you want to perform some tests.

**Comment by nikoladze** [comment]
That seems to work for now. Thanks!

**Comment by jpivarski** [comment]
Then I think we should merge the PR! I'll go approve it.
